export const ARCHETYPES = [
  "Chronically Online Overthinker",
  "Chaotic Good Goblin",
  "Matcha Fueled Perfectionist",
  "Mysterious Night Owl",
  "Caffeinated Tornado",
  "Unbothered Plant Parent",
  "Spicy Keyboard Warrior",
  "Delusional Main Character",
  "Accidental Trendsetter",
  "Reformed People Pleaser",
  "Aesthetic Spreadsheet Enthusiast",
  "Midnight Snack Sommelier",
  "Professional Procrastinator",
  "Guilt-Free Ghoster",
  "Existential Crisis Connoisseur",
  "Corporate Baddie by Day, Gremlin by Night",
  "Aggressively Wholesome Friend",
  "Overly Caffeinated Visionary",
  "Suspiciously Lucky Gambler",
  "Digitally Exhausted Sage",
  "Hopeless Romantic With a Spreadsheet",
  "Vibes-Based Decision Maker",
  "Recovering Perfectionist",
  "Unintentional Drama Magnet",
  "Low-Battery Socialite"
];

export const ROASTS = [
  "You probably know the latest TikTok drama better than you know your own relatives. Touch some grass.",
  "You run on pure adrenaline and bad decisions, but somehow it usually works out. Mostly.",
  "Your aesthetic is pristine, but we both know your closet is a disaster zone. It's okay to make a typo sometimes.",
  "You only thrive between the hours of 2 AM and 5 AM. Daylight is just a suggestion to you.",
  "You've replaced water with pure caffeine. Please slow down, the rest of us can't keep up.",
  "You have a PhD in reading the room but constantly forget to read your unread texts.",
  "You claim you don't like drama, but you're always holding the popcorn.",
  "You treat your Spotify wrapped like a personality test. We get it, you have niche taste.",
  "You apologize to inanimate objects when you bump into them, but leave actual humans on read for days.",
  "You're the friend who says 'I'm five minutes away' while still wearing a towel.",
  "You have 40 tabs open and haven't looked at 38 of them since Tuesday.",
  "You buy expensive planners just to ignore them and do whatever you want anyway.",
  "Your camera roll is 90% memes you forgot to send and 10% blurry photos of pets.",
  "You act tough but will absolutely cry if a dog ignores you on the street.",
  "You give excellent advice that you have absolutely no intention of following yourself.",
  "You consider 'liking a message' as a valid form of maintaining a friendship.",
  "You start diets on Monday and end them on Monday at 3:14 PM.",
  "You think rearranging your furniture counts as solving your life problems.",
  "You curate your playlists better than you curate your actual life.",
  "You use 'it is what it is' as a coping mechanism for things you entirely caused."
];

export const SECRET_POWERS = [
  "Can find anyone's digital footprint in 3 minutes.",
  "Creating wildly successful accidents.",
  "Color-coding their entire existence.",
  "Knowing things they shouldn't know.",
  "Completing a week's worth of work in 2 hours out of pure panic.",
  "Guessing the plot twist 10 minutes into the movie.",
  "Making extremely niche, highly accurate pop culture references.",
  "Identifying exactly which font a brand is using.",
  "Hyping up strangers in the club bathroom.",
  "Remembering embarrassing things you said in 2014.",
  "Translating absolute gibberish into perfect English.",
  "Spotting a bad vibe from three states away.",
  "Falling asleep precisely when the plot gets important.",
  "Turning any minor inconvenience into a stand-up routine.",
  "Calculating the exact tip without a calculator while mildly intoxicated."
];

export const RED_FLAGS = [
  "Communicates entirely in hyper-specific memes.",
  "Has 47 open tabs and no intention of closing them.",
  "Will judge your font choices.",
  "Takes 3-5 business days to reply to a text.",
  "Bounces legs constantly under the table.",
  "Unironically uses astrology to justify bad behavior.",
  "Leaves alarms ringing for a solid 5 minutes.",
  "Drinks iced coffee when it's literally freezing outside.",
  "Only uses lowercase letters because uppercase 'feels too aggressive'.",
  "Starts watching a 2-hour video essay at 1 AM.",
  "Orders food delivery from a place 5 minutes away.",
  "Says 'we should hang out!' with zero intention of hanging out.",
  "Eats the toppings off the pizza and leaves the bread.",
  "Needs the TV volume to end in an even number or a multiple of 5.",
  "Pauses songs right before the best part to talk."
];
